# -*- coding: utf-8 -*-
"""Python_AI_00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jtLob0w4eOHuDPrp-9kHuxcCOQf2ie4s
"""

from matplotlib import pyplot

from sklearn.cluster import KMeans

import pandas

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

score = pandas.read_csv('score2.csv', encoding='utf_8')

score

model = KMeans(n_clusters=3).fit(
    score[['English', 'Japanese']])

score['Cluster'] = model.labels_

score.to_csv('score4.csv')

score

score.plot.scatter('English', 'Japanese',
                   s=100, c=score['Cluster'],
                   edgecolor='black', figsize=(6,6))



pyplot.savefig('scatter2.png')

pyplot.show()